api_offers:
    path:     /offers
    defaults: { _controller: InamikaApiBundle:Offers:index }
    methods: [GET]

api_offers_active:
    path:     /offersActive
    defaults: { _controller: InamikaApiBundle:Offers:active }
    methods: [GET]

api_offers_search:
    path:     /offers/search
    defaults: { _controller: InamikaApiBundle:Offers:search }
    methods: [GET]

api_offers_get:
    path:     /offers/{code}
    defaults: { _controller: InamikaApiBundle:Offers:get }
    methods: [GET]

api_offers_post:
    path:     /offers
    defaults: { _controller: InamikaApiBundle:Offers:post }
    methods: [POST]

api_offers_put:
    path:     /offers/{id}
    defaults: { _controller: InamikaApiBundle:Offers:put }
    methods: [PUT]

api_offers_delete:
    path:     /offers/{id}
    defaults: { _controller: InamikaApiBundle:Offers:delete }
    methods: [DELETE]

api_offers_upload:
    path:     /upload
    defaults: { _controller: InamikaApiBundle:Offers:upload }
    methods: [POST]
