api_cart:
    path:     /cart
    defaults: { _controller: InamikaApiBundle:Cart:get }
    methods: [GET]

api_cart_post:
    path:     /cart
    defaults: { _controller: InamikaApiBundle:Cart:post }
    methods: [POST]

api_cart_put:
    path:     /cart
    defaults: { _controller: InamikaApiBundle:Cart:put }
    methods: [PUT]

api_cart_post_empty:
    path:     /cartEmpty
    defaults: { _controller: InamikaApiBundle:Cart:empty }
    methods: [POST]

api_cart_delete:
    path:     /cart/{code}
    defaults: { _controller: InamikaApiBundle:Cart:delete }
    methods: [DELETE]
